# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-03 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_writer', '0002_auto_20190920_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
