# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-05 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_writer', '0003_auto_20191003_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
